#!/usr/bin/env bash
# Install PARAGON as a systemd service (survives reboot / power loss).
set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SERVICE_NAME="${PARAGON_SERVICE_NAME:-${ROUTERBOT_SERVICE_NAME:-paragon}}"
TS_SERVICE_NAME="${PARAGON_TS_SERVICE_NAME:-${ROUTERBOT_TS_SERVICE_NAME:-paragon-tailscale}}"
UNIT_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
TS_UNIT_PATH="/etc/systemd/system/${TS_SERVICE_NAME}.service"
ENV_PATH="/etc/paragon/environment"

# User that owns CLI auth (~/.codex, ~/.cursor, etc.). Defaults to repo owner.
PARAGON_USER="${PARAGON_USER:-${ROUTERBOT_USER:-$(stat -c '%U' "$REPO_DIR")}}"
PARAGON_GROUP="${PARAGON_GROUP:-${ROUTERBOT_GROUP:-$(id -gn "$PARAGON_USER" 2>/dev/null || echo "$PARAGON_USER")}}"

pick_node() {
  if [[ -n "${PARAGON_NODE:-${ROUTERBOT_NODE:-}}" && -x "${PARAGON_NODE:-${ROUTERBOT_NODE:-}}" ]]; then
    echo "${PARAGON_NODE:-${ROUTERBOT_NODE:-}}"
    return
  fi
  if command -v node >/dev/null 2>&1; then
    local n
    n="$(command -v node)"
    # Cursor's bundled node is not suitable for a system service
    if [[ "$n" != *".cursor-server"* ]]; then
      echo "$n"
      return
    fi
  fi
  if [[ -x /usr/bin/node ]]; then
    echo /usr/bin/node
    return
  fi
  local nvm_glob="${HOME}/.nvm/versions/node/"*/bin/node
  # shellcheck disable=SC2086
  for candidate in $nvm_glob; do
    if [[ -x "$candidate" ]]; then
      echo "$candidate"
      return
    fi
  done
  echo "ERROR: Could not find node. Set PARAGON_NODE=/path/to/node" >&2
  exit 1
}

NODE_BIN="$(sudo -u "$PARAGON_USER" bash -c "$(declare -f pick_node); pick_node")"

build_path() {
  local home
  home="$(getent passwd "$PARAGON_USER" | cut -d: -f6)"
  local parts=()
  # nvm default node (newest installed)
  local nvm_glob="${home}/.nvm/versions/node/"*/bin
  # shellcheck disable=SC2086
  for d in $nvm_glob; do
    [[ -d "$d" ]] && parts+=("$d")
  done
  parts+=(
    "${home}/.local/bin"
    /usr/local/bin
    /usr/bin
    /bin
    # Several provider CLIs (codex, chromium, etc.) ship as snap packages on
    # this host — without this, spawn("codex", ...) fails ENOENT even when
    # `codex` resolves fine in an interactive login shell.
    /snap/bin
  )
  local IFS=:
  echo "${parts[*]}"
}

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Re-running with sudo to install ${UNIT_PATH} ..."
  exec sudo env \
    PARAGON_USER="$PARAGON_USER" \
    PARAGON_GROUP="$PARAGON_GROUP" \
    PARAGON_NODE="${PARAGON_NODE:-${ROUTERBOT_NODE:-}}" \
    "$0" "$@"
fi

mkdir -p /etc/paragon
PATH_VALUE="$(build_path)"

# Read the actual configured ports out of data/config.json rather than
# leaving PARAGON_PORT/PARAGON_TAILSCALE_*_PORT unset. Previously
# tailscale-setup.sh (invoked by paragon-tailscale.service) fell back to its
# own hardcoded defaults (4117/9420/10000) whenever these env vars were
# absent — silently decoupling "what Tailscale exposes" from "what
# config.json actually says", regardless of the configured port. See
# docs/evidence/PARAGON-D-002C-CUTOVER.md for the incident this caused.
CONFIG_PATH="${REPO_DIR}/data/config.json"
read_config_port() {
  local key="$1"
  local fallback="$2"
  if [[ -f "$CONFIG_PATH" ]]; then
    sudo -u "$PARAGON_USER" node -e "
      const fs = require('fs');
      try {
        const c = JSON.parse(fs.readFileSync('${CONFIG_PATH}', 'utf8'));
        const v = c.server && c.server['${key}'];
        console.log(Number.isFinite(v) ? v : ${fallback});
      } catch { console.log(${fallback}); }
    " 2>/dev/null || echo "$fallback"
  else
    echo "$fallback"
  fi
}
PARAGON_LOCAL_PORT="$(read_config_port port 4117)"
PARAGON_SERVE_PORT="$(read_config_port tailscaleServePort 9420)"
PARAGON_FUNNEL_PORT="$(read_config_port tailscaleFunnelPort 10000)"

cat >"$ENV_PATH" <<EOF
# Generated by scripts/install-systemd.sh — edit and run: sudo systemctl restart paragon
HOME=$(getent passwd "$PARAGON_USER" | cut -d: -f6)
PATH=${PATH_VALUE}
NODE_ENV=production
PARAGON_PORT=${PARAGON_LOCAL_PORT}
PARAGON_TAILSCALE_SERVE_PORT=${PARAGON_SERVE_PORT}
PARAGON_TAILSCALE_FUNNEL_PORT=${PARAGON_FUNNEL_PORT}
EOF
chmod 644 "$ENV_PATH"

sed \
  -e "s|%PARAGON_USER%|${PARAGON_USER}|g" \
  -e "s|%PARAGON_GROUP%|${PARAGON_GROUP}|g" \
  -e "s|%PARAGON_DIR%|${REPO_DIR}|g" \
  -e "s|%NODE_BIN%|${NODE_BIN}|g" \
  "${REPO_DIR}/deploy/paragon.service" >"$UNIT_PATH"

sed \
  -e "s|%PARAGON_DIR%|${REPO_DIR}|g" \
  -e "s|%PARAGON_LOCAL_PORT%|${PARAGON_LOCAL_PORT}|g" \
  -e "s|%PARAGON_SERVE_PORT%|${PARAGON_SERVE_PORT}|g" \
  -e "s|%PARAGON_FUNNEL_PORT%|${PARAGON_FUNNEL_PORT}|g" \
  "${REPO_DIR}/deploy/paragon-tailscale.service" >"$TS_UNIT_PATH"

systemctl daemon-reload
systemctl enable "${TS_SERVICE_NAME}.service"
systemctl enable "${SERVICE_NAME}.service"
systemctl start "${TS_SERVICE_NAME}.service" || true
systemctl restart "${SERVICE_NAME}.service"

echo ""
echo "Installed ${UNIT_PATH}"
echo "Environment: ${ENV_PATH}"
echo "User:        ${PARAGON_USER}"
echo "Node:        ${NODE_BIN}"
echo ""
systemctl status "${SERVICE_NAME}.service" --no-pager -l || true
echo ""
echo "Useful commands:"
echo "  ./scripts/check-paragon.sh"
echo "  sudo systemctl status ${SERVICE_NAME}"
echo "  sudo systemctl status ${TS_SERVICE_NAME}"
echo "  sudo journalctl -u ${SERVICE_NAME} -f"
echo "  sudo systemctl restart ${SERVICE_NAME}"
