/** Regex sources for task routing — also copied into defaultConfig.taskPatterns. */

function routePattern(parts) {
  return String.raw`\b(?:${parts.join("|")})\b`;
}

const ASK = [
  String.raw`what(?:'s|s| is| are| were| was| would| will| do| does| did| can| could| should| might)`,
  String.raw`how (?:do|does|did|can|could|would|should|will|to|is|are|was|were|come|about|much|many|long|often)`,
  String.raw`why (?:is|are|was|were|do|does|did|would|should|can|could|will|not|don't|doesn't)`,
  String.raw`when (?:is|are|was|were|do|does|did|should|would|can|could|to|will)`,
  String.raw`where (?:is|are|was|were|do|does|did|can|could|should|would|to|from)`,
  String.raw`who (?:is|are|was|were|should|can|could|would|will)`,
  String.raw`which (?:is|are|was|were|one|should|would|can|could|do|does)`,
  String.raw`whose (?:is|are|was|were)`,
  String.raw`whom (?:should|can|could|would|do|does|is|are)`,
  String.raw`can you (?:explain|tell|clarify|help|describe|summarize|summarise|list|show|walk|outline)`,
  String.raw`could you (?:explain|tell|clarify|help|describe|summarize|summarise|list|show|walk|outline)`,
  String.raw`would you (?:explain|tell|clarify|help|describe|say|mind)`,
  String.raw`will you (?:explain|tell|clarify|help|describe)`,
  String.raw`please (?:explain|tell|clarify|describe|summarize|summarise)`,
  String.raw`tell me (?:about|how|why|what|if|when|where|which|more)`,
  String.raw`help me understand`,
  String.raw`help me figure out`,
  String.raw`give me an overview`,
  String.raw`overview of`,
  String.raw`high[- ]level overview`,
  String.raw`describe (?:what|how|why|the|this|that)`,
  String.raw`definition of`,
  String.raw`define (?:the|what|a|an)`,
  String.raw`meaning of`,
  String.raw`difference between`,
  String.raw`differences between`,
  String.raw`compared to`,
  String.raw`compare (?:the|these|this|that|and|with)`,
  String.raw`comparison (?:of|between)`,
  String.raw`versus`,
  String.raw`\bvs\.?\b`,
  String.raw`is it (?:possible|better|safe|worth|correct|true|normal|expected|recommended)`,
  String.raw`are (?:there|they|we|you)`,
  String.raw`is (?:there|this|that|it|he|she)`,
  String.raw`should I`,
  String.raw`should we`,
  String.raw`would it`,
  String.raw`would you`,
  String.raw`do I need`,
  String.raw`do we need`,
  String.raw`does (?:this|that|it) (?:need|require|mean|do|work)`,
  String.raw`any idea`,
  String.raw`any thoughts`,
  String.raw`thoughts on`,
  String.raw`your take on`,
  String.raw`opinion on`,
  String.raw`what do you think`,
  String.raw`what would you`,
  String.raw`what would happen`,
  String.raw`what if`,
  String.raw`what about`,
  String.raw`how about`,
  String.raw`how come`,
  String.raw`how so`,
  String.raw`curious about`,
  String.raw`wondering (?:if|why|how|what|whether)`,
  String.raw`wonder if`,
  String.raw`fill me in`,
  String.raw`bring me up to speed`,
  String.raw`catch me up`,
  String.raw`pros and cons`,
  String.raw`advantages and disadvantages`,
  String.raw`benefits and drawbacks`,
  String.raw`worth it`,
  String.raw`make sense to`,
  String.raw`good idea to`,
  String.raw`bad idea to`,
  String.raw`examples of`,
  String.raw`example of`,
  String.raw`list the`,
  String.raw`name the`,
  String.raw`hypothetically`,
  String.raw`generally speaking`,
  String.raw`in general`,
  String.raw`quick question`,
  String.raw`clarify`,
  String.raw`clarification on`,
  String.raw`question about`,
  String.raw`summari[sz]e (?:this|the|what|how|why)`,
  String.raw`what does .+ mean`,
  String.raw`what did .+ mean`,
  String.raw`what is the (?:purpose|point|role|reason|difference|impact)`,
  String.raw`what are the (?:pros|cons|benefits|risks|options|steps|requirements)`,
  String.raw`am I (?:right|correct|missing|understanding)`,
  String.raw`are we (?:missing|using|doing|talking about)`,
  String.raw`do you know (?:if|why|how|what|whether)`,
  String.raw`can you clarify`,
  String.raw`could you clarify`,
  String.raw`explain whether`,
  String.raw`isn't (?:this|that|it)`,
  String.raw`doesn't (?:this|that|it)`,
  String.raw`didn't (?:this|that|it)`
];

const AGENT = [
  String.raw`refactor`,
  String.raw`apply (?:the )?changes`,
  String.raw`apply (?:the )?(?:patch|fix|update|suggestion|feedback)`,
  String.raw`edit (?:the )?files?`,
  String.raw`modify (?:the )?code`,
  String.raw`make the changes`,
  String.raw`make edits`,
  String.raw`make changes to`,
  String.raw`implement (?:the )?(?:fix|change|feature|plan|solution|update|refactor)`,
  String.raw`update (?:the )?(?:file|files|code|implementation|function|class|module|component|handler|endpoint|logic|config|import|imports|test|tests|dependency|dependencies|version|package|packages|schema|types|interface|interfaces|UI|api|API|route|routes|script|scripts|workflow|pipeline|Dockerfile|CI|workflow|setting|settings)`,
  String.raw`change (?:the )?(?:code|implementation|file|logic|behavior|behaviour|default|config|setting)`,
  String.raw`patch (?:the )?`,
  String.raw`rewrite (?:the )?`,
  String.raw`\bmigrate\b`,
  String.raw`migration of`,
  String.raw`rename (?:the )?`,
  String.raw`move (?:the )?file`,
  String.raw`move (?:this|it|the) to`,
  String.raw`delete (?:the )?file`,
  String.raw`remove (?:the )?(?:file|code|function|class|module|component|dead code|unused|deprecated|legacy)`,
  String.raw`drop (?:the )?(?:file|code|feature|support for)`,
  String.raw`strip (?:out|away)`,
  String.raw`swap (?:out|in|the)`,
  String.raw`replace (?:the )?(?:file|code|implementation|library|dependency|function|class|module)`,
  String.raw`insert (?:into|the)`,
  String.raw`append (?:to|the)`,
  String.raw`prepend (?:to|the)`,
  String.raw`add (?:a )?(?:feature|file|module|component|handler|endpoint|test|hook|callback|button|field|column|table|route|import|logging|validation|check|guard|middleware|type|interface|env var|environment variable|config option)`,
  String.raw`wire up`,
  String.raw`wire in`,
  String.raw`plug in`,
  String.raw`hook up`,
  String.raw`integrate (?:with|into)`,
  String.raw`connect (?:to|the|this)`,
  String.raw`set up (?:the )?`,
  String.raw`configure (?:the )?`,
  String.raw`fix (?:this|the) (?:file|module|component|handler|bug|issue|error|test|build|lint|type error|import|CI|pipeline|regression)`,
  String.raw`fix (?:the )?(?:typo|spelling|formatting|indentation|lint|types|tests|build|CI|pipeline|merge conflict|conflict|regression|flaky test)`,
  String.raw`in (?:this|the) (?:repo|codebase|project|file|directory|folder|branch|PR|pull request)`,
  String.raw`on (?:this|the) (?:PR|pull request)`,
  String.raw`apply (?:the )?patch`,
  String.raw`get (?:it|this) working`,
  String.raw`make (?:it|this) work`,
  String.raw`carry out`,
  String.raw`execute (?:the )?plan`,
  String.raw`follow through`,
  String.raw`do the (?:refactor|migration|update|implementation|work|change|fix|cleanup|clean up)`,
  String.raw`implement this`,
  String.raw`code changes`,
  String.raw`touch (?:the )?file`,
  String.raw`open (?:a )?PR`,
  String.raw`commit (?:the )?changes`,
  String.raw`push (?:the )?changes`,
  String.raw`merge (?:the )?changes`,
  String.raw`resolve (?:the )?(?:conflict|conflicts|merge conflict|comment|comments|review comment|thread)`,
  String.raw`rebase`,
  String.raw`cherry[- ]pick`,
  String.raw`squash (?:the )?commit`,
  String.raw`clean up (?:the )?(?:code|file|imports|tests|repo)`,
  String.raw`cleanup (?:the )?`,
  String.raw`tidy up`,
  String.raw`format (?:the )?(?:file|code)`,
  String.raw`autofix`,
  String.raw`lint fix`,
  String.raw`optimize (?:the )?`,
  String.raw`hotfix`,
  String.raw`hot fix`,
  String.raw`roll back`,
  String.raw`rollback`,
  String.raw`revert (?:the )?(?:change|commit|PR|merge)`,
  String.raw`undo (?:the )?(?:change|commit|merge)`,
  String.raw`align (?:with|to)`,
  String.raw`sync (?:with|to)`,
  String.raw`port (?:this|the|it) (?:from|to)`,
  String.raw`scaffold out`,
  String.raw`stub out`,
  String.raw`flesh out (?:the )?(?:implementation|feature|module|handler)`,
  String.raw`fill in (?:the )?(?:implementation|missing|gaps|TODO|stub)`,
  String.raw`finish implementing`,
  String.raw`complete the implementation`,
  String.raw`ship (?:this|it|the change)`,
  String.raw`land (?:the )?(?:change|PR|feature)`,
  String.raw`address (?:the )?(?:review comments|review comment|comments|comment|feedback|review|suggestion|suggestions)`,
  String.raw`apply review comments`,
  String.raw`fix review comments`,
  String.raw`incorporate (?:the )?feedback`,
  String.raw`apply suggestions`,
  String.raw`update imports`,
  String.raw`fix imports`,
  String.raw`add error handling`,
  String.raw`handle (?:the )?edge case`,
  String.raw`enable (?:the )?feature`,
  String.raw`disable (?:the )?feature`,
  String.raw`extract (?:to|into|the)`,
  String.raw`inline (?:the )?`,
  String.raw`split (?:the )?file`,
  String.raw`combine (?:the )?files?`,
  String.raw`remove unused`,
  String.raw`dead code`,
  String.raw`adjust (?:the )?tests?`,
  String.raw`update tests for`,
  String.raw`bump (?:the )?version`,
  String.raw`version bump`,
  String.raw`hands[- ]on`,
  String.raw`make it so`,
  String.raw`put this in the codebase`,
  String.raw`check this into`,
  String.raw`commit and push`
];

const MULTITASK = [
  String.raw`parallel(?:ize|ise|ly)?`,
  String.raw`multitask`,
  String.raw`multi-task`,
  String.raw`multiple tasks`,
  String.raw`several tasks`,
  String.raw`many tasks`,
  String.raw`batch (?:of )?(?:tasks|jobs|requests|operations|changes)`,
  String.raw`concurrent(?:ly)?`,
  String.raw`concurrency`,
  String.raw`workers?`,
  String.raw`worker pool`,
  String.raw`thread pool`,
  String.raw`multiprocess`,
  String.raw`multithread`,
  String.raw`simultaneous(?:ly)?`,
  String.raw`at the same time`,
  String.raw`in parallel`,
  String.raw`fan out`,
  String.raw`fan-out`,
  String.raw`scatter(?:-gather)?`,
  String.raw`delegate (?:to )?(?:workers|agents|tasks|subagents|sub-agents)`,
  String.raw`subagents?`,
  String.raw`sub-agents?`,
  String.raw`subtasks?`,
  String.raw`sub-tasks?`,
  String.raw`workstreams?`,
  String.raw`pipeline (?:of )?(?:tasks|jobs)`,
  String.raw`orchestrat(?:e|ion|ing)`,
  String.raw`split into tasks`,
  String.raw`divide and conquer`,
  String.raw`divide the work`,
  String.raw`split the work`,
  String.raw`partition (?:the )?work`,
  String.raw`distribute (?:the )?work`,
  String.raw`run (?:these|them|all|each) (?:in parallel|concurrently|at once)`,
  String.raw`multiple agents`,
  String.raw`agent swarm`,
  String.raw`fleet of agents`,
  String.raw`async jobs?`,
  String.raw`background jobs? concurrently`,
  String.raw`queue of tasks`,
  String.raw`task queue`,
  String.raw`job queue`,
  String.raw`spawn workers`,
  String.raw`map-reduce`,
  String.raw`work (?:items|packages) in parallel`,
  String.raw`parallel workers`,
  String.raw`concurrent execution`,
  String.raw`bulk (?:process|run|execute|update)`,
  String.raw`en masse`,
  String.raw`for each of these`,
  String.raw`each of these (?:separately|in parallel|concurrently)`,
  String.raw`all of these (?:at once|in parallel|concurrently)`,
  String.raw`split across (?:workers|agents|tasks)`,
  String.raw`load balance`,
  String.raw`team of agents`,
  String.raw`assign tasks`,
  String.raw`task list execution`,
  String.raw`run the list`,
  String.raw`process (?:these|them|all) (?:in parallel|concurrently|together)`,
  String.raw`parallel batch`,
  String.raw`concurrent batch`,
  String.raw`multi-agent`,
  String.raw`multi agent`
];

const DEBUG = [
  String.raw`error`,
  String.raw`errors`,
  String.raw`bug`,
  String.raw`bugs`,
  String.raw`fix(?:ing)? the bug`,
  String.raw`failing`,
  String.raw`fail(?:ed|ure|s|ing)?`,
  String.raw`stack trace`,
  String.raw`traceback`,
  String.raw`exception`,
  String.raw`regression`,
  String.raw`diagnose`,
  String.raw`debug(?:ging)?`,
  String.raw`crash(?:ed|es|ing)?`,
  String.raw`broken`,
  String.raw`doesn't work`,
  String.raw`does not work`,
  String.raw`didn't work`,
  String.raw`not working`,
  String.raw`won't work`,
  String.raw`isn't working`,
  String.raw`stopped working`,
  String.raw`no longer works`,
  String.raw`used to work`,
  String.raw`worked before`,
  String.raw`troubleshoot`,
  String.raw`root cause`,
  String.raw`investigate (?:why|the|this|what)`,
  String.raw`TypeError`,
  String.raw`ReferenceError`,
  String.raw`SyntaxError`,
  String.raw`RangeError`,
  String.raw`NameError`,
  String.raw`ValueError`,
  String.raw`KeyError`,
  String.raw`IndexError`,
  String.raw`AttributeError`,
  String.raw`ImportError`,
  String.raw`ModuleNotFoundError`,
  String.raw`NullPointer`,
  String.raw`segfault`,
  String.raw`panic(?:ked)?`,
  String.raw`assertion (?:failed|error|failure)`,
  String.raw`unexpected (?:behavior|behaviour|result|output|value|response|error)`,
  String.raw`what(?:'s| is) wrong`,
  String.raw`what went wrong`,
  String.raw`figure out why`,
  String.raw`find out why`,
  String.raw`repro(?:duce|duction)?`,
  String.raw`replication steps`,
  String.raw`repro steps`,
  String.raw`minimal repro`,
  String.raw`replicate the (?:bug|issue|error|failure|problem)`,
  String.raw`isolate the issue`,
  String.raw`narrow (?:it )?down`,
  String.raw`broken build`,
  String.raw`build (?:failed|failing|breaks|error|broken)`,
  String.raw`won't build`,
  String.raw`doesn't build`,
  String.raw`does not build`,
  String.raw`CI (?:failed|failing|red|broken|error)`,
  String.raw`pipeline (?:failed|failing|broken)`,
  String.raw`lint error`,
  String.raw`lint failed`,
  String.raw`compiler error`,
  String.raw`compile error`,
  String.raw`compilation (?:failed|error|failure)`,
  String.raw`type error`,
  String.raw`typecheck failed`,
  String.raw`type check failed`,
  String.raw`test(?:s)? (?:failed|failing|error|broken)`,
  String.raw`failing test`,
  String.raw`flaky test`,
  String.raw`\bflaky\b`,
  String.raw`production (?:only|bug|issue|error)`,
  String.raw`prod (?:only|bug|issue|error)`,
  String.raw`intermittent (?:failure|bug|issue|error)`,
  String.raw`sporadic (?:failure|bug|issue|error)`,
  String.raw`sometimes fails`,
  String.raw`hangs`,
  String.raw`hanging`,
  String.raw`freeze(?:s|d|ing)?`,
  String.raw`frozen`,
  String.raw`stuck`,
  String.raw`deadlock`,
  String.raw`race condition`,
  String.raw`memory leak`,
  String.raw`out of memory`,
  String.raw`\bOOM\b`,
  String.raw`leak(?:ing)? memory`,
  String.raw`corrupt(?:ed|ion)?`,
  String.raw`invalid state`,
  String.raw`inconsistent`,
  String.raw`mismatch`,
  String.raw`off by one`,
  String.raw`wrong output`,
  String.raw`incorrect result`,
  String.raw`unexpected value`,
  String.raw`\bNaN\b`,
  String.raw`500 error`,
  String.raw`404 error`,
  String.raw`403 error`,
  String.raw`401 error`,
  String.raw`400 error`,
  String.raw`502 error`,
  String.raw`503 error`,
  String.raw`504 error`,
  String.raw`timeout (?:error|failed|expired|ing)?`,
  String.raw`ETIMEDOUT`,
  String.raw`ECONNREFUSED`,
  String.raw`ECONNRESET`,
  String.raw`connection refused`,
  String.raw`connection reset`,
  String.raw`permission denied`,
  String.raw`access denied`,
  String.raw`unauthorized`,
  String.raw`forbidden`,
  String.raw`bad gateway`,
  String.raw`internal server error`,
  String.raw`DNS error`,
  String.raw`SSL error`,
  String.raw`TLS error`,
  String.raw`certificate error`,
  String.raw`cannot find module`,
  String.raw`module not found`,
  String.raw`import error`,
  String.raw`dependency error`,
  String.raw`unresolved import`,
  String.raw`undefined is not`,
  String.raw`cannot read propert`,
  String.raw`is not a function`,
  String.raw`is not defined`,
  String.raw`is not iterable`,
  String.raw`segmentation fault`,
  String.raw`core dump`,
  String.raw`stack overflow`,
  String.raw`stderr`,
  String.raw`stdout shows error`,
  String.raw`error message`,
  String.raw`error log`,
  String.raw`logs show`,
  String.raw`log says`,
  String.raw`red screen`,
  String.raw`white screen`,
  String.raw`blank screen`,
  String.raw`production bug`,
  String.raw`prod issue`,
  String.raw`staging bug`,
  String.raw`customer report`,
  String.raw`user reported`,
  String.raw`breaks when`,
  String.raw`fails when`,
  String.raw`fails on`,
  String.raw`only fails in`,
  String.raw`works locally but`,
  String.raw`started happening after`,
  String.raw`regression since`,
  String.raw`bisect`,
  String.raw`git bisect`,
  String.raw`why is this happening`,
  String.raw`why does this happen`,
  String.raw`help debug`,
  String.raw`need to debug`,
  String.raw`something broke`,
  String.raw`something is broken`,
  String.raw`something's wrong`
];

const REVIEW = [
  String.raw`review`,
  String.raw`code review`,
  String.raw`peer review`,
  String.raw`look over`,
  String.raw`look at my (?:code|PR|changes|work|patch|diff|implementation)`,
  String.raw`check my (?:code|PR|changes|work|patch|diff|implementation)`,
  String.raw`feedback on`,
  String.raw`critique`,
  String.raw`audit`,
  String.raw`sanity check`,
  String.raw`gut check`,
  String.raw`smell test`,
  String.raw`second pair of eyes`,
  String.raw`fresh eyes on`,
  String.raw`spot (?:issues|problems|bugs|mistakes|errors)`,
  String.raw`find (?:issues|problems|bugs|mistakes|errors) in`,
  String.raw`assess (?:the )?(?:code|changes|risk|approach|design|implementation|PR)`,
  String.raw`evaluate (?:the )?(?:code|approach|design|changes|implementation|PR)`,
  String.raw`double check`,
  String.raw`triple check`,
  String.raw`verify (?:the )?(?:changes|code|approach|implementation)`,
  String.raw`validate (?:the )?(?:approach|design|changes|implementation)`,
  String.raw`diff`,
  String.raw`pull request`,
  String.raw`\bpr\b`,
  String.raw`merge request`,
  String.raw`\bmr\b`,
  String.raw`risk(?:s)?`,
  String.raw`security(?: review| audit)?`,
  String.raw`vulnerabilit(?:y|ies)`,
  String.raw`\bCVE\b`,
  String.raw`threat model`,
  String.raw`pen test`,
  String.raw`pentest`,
  String.raw`red team`,
  String.raw`OWASP`,
  String.raw`SAST`,
  String.raw`DAST`,
  String.raw`supply chain`,
  String.raw`dependency audit`,
  String.raw`license check`,
  String.raw`code smell`,
  String.raw`anti-pattern`,
  String.raw`best practice`,
  String.raw`nitpick`,
  String.raw`nits?`,
  String.raw`\bLGTM\b`,
  String.raw`changes requested`,
  String.raw`PR comments`,
  String.raw`review comments`,
  String.raw`before merge`,
  String.raw`ready to merge`,
  String.raw`good to merge`,
  String.raw`ship it`,
  String.raw`approve (?:this )?(?:PR|change|merge)`,
  String.raw`sign off on`,
  String.raw`review (?:this )?(?:PR|diff|patch|change|code|implementation)`,
  String.raw`what do you think of (?:this|my) code`,
  String.raw`roast my code`,
  String.raw`tear apart`,
  String.raw`pick apart`,
  String.raw`security audit`,
  String.raw`compliance check`,
  String.raw`regression risk`,
  String.raw`performance review`,
  String.raw`scalability review`,
  String.raw`maintainability`,
  String.raw`readability review`,
  String.raw`naming review`,
  String.raw`API review`,
  String.raw`design review`,
  String.raw`architectural review`,
  String.raw`architecture review`,
  String.raw`pre-merge review`,
  String.raw`post-implementation review`,
  String.raw`reviewer feedback`,
  String.raw`requested changes`,
  String.raw`blocking issue`,
  String.raw`any concerns`,
  String.raw`any issues with`,
  String.raw`thorough review`,
  String.raw`line by line`,
  String.raw`pass over`,
  String.raw`once-over`,
  String.raw`quality gate`,
  String.raw`code standards`,
  String.raw`style guide`,
  String.raw`lint review`,
  String.raw`PR review`,
  String.raw`pull request review`,
  String.raw`merge review`,
  String.raw`change review`,
  String.raw`implementation review`
];

const DOCS = [
  String.raw`readme`,
  String.raw`readmes`,
  String.raw`\bdocs?\b`,
  String.raw`documentation`,
  String.raw`docstrings?`,
  String.raw`docblocks?`,
  String.raw`changelog`,
  String.raw`change log`,
  String.raw`release notes?`,
  String.raw`write-up`,
  String.raw`writeup`,
  String.raw`API docs?`,
  String.raw`api reference`,
  String.raw`API reference`,
  String.raw`reference docs?`,
  String.raw`user guide`,
  String.raw`developer guide`,
  String.raw`dev guide`,
  String.raw`tutorial`,
  String.raw`how-to guide`,
  String.raw`howto guide`,
  String.raw`onboarding`,
  String.raw`contributing`,
  String.raw`license file`,
  String.raw`wiki page`,
  String.raw`internal wiki`,
  String.raw`knowledge base`,
  String.raw`markdown doc`,
  String.raw`write documentation`,
  String.raw`write docs`,
  String.raw`document (?:this|the|how|why|what|the API|the feature|the process)`,
  String.raw`update (?:the )?(?:readme|docs|documentation|changelog|release notes|wiki|guide)`,
  String.raw`add comments?`,
  String.raw`JSDoc`,
  String.raw`doc comment`,
  String.raw`specification doc`,
  String.raw`technical writing`,
  String.raw`migration guide`,
  String.raw`upgrade guide`,
  String.raw`setup guide`,
  String.raw`install guide`,
  String.raw`deployment guide`,
  String.raw`troubleshooting guide`,
  String.raw`operator guide`,
  String.raw`runbook`,
  String.raw`playbook`,
  String.raw`FAQ`,
  String.raw`glossary`,
  String.raw`README\.md`,
  String.raw`inline docs?`,
  String.raw`inline documentation`,
  String.raw`comment (?:the )?(?:code|function|class|method|module|API)`,
  String.raw`explain in the docs`,
  String.raw`usage example`,
  String.raw`usage docs`,
  String.raw`examples section`,
  String.raw`getting started guide`,
  String.raw`quickstart`,
  String.raw`quick start`,
  String.raw`architecture doc`,
  String.raw`design doc for users`,
  String.raw`handbook`,
  String.raw`cookbook`,
  String.raw`man page`,
  String.raw`manpage`,
  String.raw`swagger doc`,
  String.raw`openapi doc`,
  String.raw`OpenAPI documentation`,
  String.raw`add examples to`,
  String.raw`developer docs`,
  String.raw`end user docs`,
  String.raw`release documentation`,
  String.raw`version notes`,
  String.raw`deprecation notice`,
  String.raw`breaking changes doc`,
  String.raw`CONTRIBUTING\.md`,
  String.raw`SECURITY\.md`,
  String.raw`annotate`,
  String.raw`add docstring to`,
  String.raw`comment every`,
  String.raw`docs page`,
  String.raw`documentation page`,
  String.raw`standard operating procedure`,
  String.raw`\bSOP\b`,
  String.raw`write up how to`,
  String.raw`document the API`,
  String.raw`document the feature`,
  String.raw`improve the docs`,
  String.raw`refresh the docs`,
  String.raw`docs cleanup`
];

const PLAN = [
  String.raw`plan(?:ning)?`,
  String.raw`architecture`,
  String.raw`architectural`,
  String.raw`system design`,
  String.raw`solution design`,
  String.raw`target architecture`,
  String.raw`high[- ]level`,
  String.raw`design (?:doc|document|approach|pattern|system|review|proposal)`,
  String.raw`approach for`,
  String.raw`strategy`,
  String.raw`strateg(?:y|ize|izing)`,
  String.raw`break down`,
  String.raw`roadmap`,
  String.raw`blueprint`,
  String.raw`spec(?:ification)?`,
  String.raw`proposal`,
  String.raw`\bRFC\b`,
  String.raw`trade[- ]offs?`,
  String.raw`tradeoff`,
  String.raw`options for`,
  String.raw`evaluate options`,
  String.raw`compare approaches`,
  String.raw`compare options`,
  String.raw`decision matrix`,
  String.raw`build vs buy`,
  String.raw`build or buy`,
  String.raw`cost benefit`,
  String.raw`data model`,
  String.raw`schema design`,
  String.raw`migration plan`,
  String.raw`rollout plan`,
  String.raw`launch plan`,
  String.raw`go-live plan`,
  String.raw`cutover plan`,
  String.raw`rollback plan`,
  String.raw`mitigation plan`,
  String.raw`contingency plan`,
  String.raw`phased (?:approach|rollout|plan|migration)`,
  String.raw`milestone(?:s)?`,
  String.raw`epic(?:s)?`,
  String.raw`sprint plan`,
  String.raw`requirements`,
  String.raw`scope(?: of work)?`,
  String.raw`feasibility`,
  String.raw`brainstorm`,
  String.raw`think through`,
  String.raw`outline (?:the )?(?:plan|approach|steps|strategy|architecture|solution)`,
  String.raw`steps to`,
  String.raw`how should we`,
  String.raw`best way to`,
  String.raw`structure for`,
  String.raw`organize the`,
  String.raw`before coding`,
  String.raw`before implementing`,
  String.raw`before we code`,
  String.raw`before building`,
  String.raw`design decision`,
  String.raw`\bADR\b`,
  String.raw`decision record`,
  String.raw`implementation plan`,
  String.raw`project plan`,
  String.raw`technical plan`,
  String.raw`game plan`,
  String.raw`step-by-step plan`,
  String.raw`work breakdown`,
  String.raw`\bWBS\b`,
  String.raw`priorit(?:y|ize|ization)`,
  String.raw`sequence of work`,
  String.raw`phasing`,
  String.raw`plan of attack`,
  String.raw`discovery phase`,
  String.raw`spike`,
  String.raw`technical approach`,
  String.raw`future state`,
  String.raw`current state`,
  String.raw`gap analysis`,
  String.raw`assessment of options`,
  String.raw`effort estimate`,
  String.raw`sizing`,
  String.raw`t-shirt size`,
  String.raw`story breakdown`,
  String.raw`user stories`,
  String.raw`acceptance criteria`,
  String.raw`non-functional requirements`,
  String.raw`\bNFRs\b`,
  String.raw`constraints and assumptions`,
  String.raw`assumptions and risks`,
  String.raw`risk assessment`,
  String.raw`incremental rollout`,
  String.raw`feature flag strategy`,
  String.raw`testing strategy`,
  String.raw`deployment strategy`,
  String.raw`observability plan`,
  String.raw`monitoring plan`,
  String.raw`capacity planning`,
  String.raw`decomposition`,
  String.raw`slice the work`,
  String.raw`order of operations`,
  String.raw`sequencing`,
  String.raw`dependencies between`,
  String.raw`critical path`,
  String.raw`long term vision`,
  String.raw`north star`,
  String.raw`90 day plan`,
  String.raw`quarterly plan`,
  String.raw`phase 1`,
  String.raw`phase 2`,
  String.raw`stage 1`,
  String.raw`stage 2`,
  String.raw`propose a`,
  String.raw`proposal for`,
  String.raw`strawman`,
  String.raw`straw man`,
  String.raw`sketch out (?:a|the|an) (?:plan|approach|architecture|strategy|solution)`,
  String.raw`high level plan`,
  String.raw`low level design`,
  String.raw`\bHLD\b`,
  String.raw`\bLLD\b`,
  String.raw`whiteboard`,
  String.raw`whiteboarding`,
  String.raw`what's the plan`,
  String.raw`what is the plan`,
  String.raw`how should we approach`,
  String.raw`how do we approach`,
  String.raw`planning session`,
  String.raw`architecture session`
];

const EXPLAIN = [
  String.raw`explain (?:how|why|what|the|this|that|to me|whether|when|where)`,
  String.raw`why (?:does|do|is|are|would|should|can|could|will|did|was|were)`,
  String.raw`how (?:does|do|can|would|should|will|did) .+ work`,
  String.raw`what does .+ do`,
  String.raw`what happens when`,
  String.raw`what would happen if`,
  String.raw`walk me through (?:how|the|this|why|what)`,
  String.raw`teach me`,
  String.raw`help me understand (?:how|why|what|the|this)`,
  String.raw`break down how`,
  String.raw`break it down for me`,
  String.raw`intuition (?:for|behind|about)`,
  String.raw`conceptually`,
  String.raw`in plain english`,
  String.raw`in simple terms`,
  String.raw`in simpler terms`,
  String.raw`for a beginner`,
  String.raw`for beginners`,
  String.raw`ELI5`,
  String.raw`like I'm five`,
  String.raw`like I am five`,
  String.raw`dumb it down`,
  String.raw`without jargon`,
  String.raw`no jargon`,
  String.raw`underlying mechanism`,
  String.raw`reason (?:for|behind)`,
  String.raw`motivation behind`,
  String.raw`rationale for`,
  String.raw`justification for`,
  String.raw`purpose of`,
  String.raw`point of`,
  String.raw`role of`,
  String.raw`elaborate on`,
  String.raw`expand on`,
  String.raw`detail how`,
  String.raw`describe how`,
  String.raw`explain the (?:logic|flow|process|architecture|design|reason|purpose|behavior|behaviour)`,
  String.raw`how it works`,
  String.raw`why it works`,
  String.raw`why we (?:use|chose|need|have|did)`,
  String.raw`what's going on`,
  String.raw`what is happening`,
  String.raw`what is going on`,
  String.raw`unpack (?:this|the)`,
  String.raw`demystify`,
  String.raw`make sense of`,
  String.raw`clarify how`,
  String.raw`clarify why`,
  String.raw`step by step explanation`,
  String.raw`walkthrough of how`,
  String.raw`lifecycle of`,
  String.raw`flow of`,
  String.raw`sequence of events`,
  String.raw`mental model`,
  String.raw`big picture`,
  String.raw`zoom out`,
  String.raw`context for why`,
  String.raw`background on why`,
  String.raw`history of why`,
  String.raw`help me grok`,
  String.raw`\bgrok\b`,
  String.raw`understand the concept`,
  String.raw`understand why`,
  String.raw`understand how`,
  String.raw`what am I missing`,
  String.raw`what should I know about`,
  String.raw`primer on`,
  String.raw`introduction to`,
  String.raw`intro to`,
  String.raw`101`,
  String.raw`fundamentals of`,
  String.raw`basics of`,
  String.raw`core idea`,
  String.raw`key idea`,
  String.raw`main idea behind`,
  String.raw`explain like`,
  String.raw`can you explain`,
  String.raw`could you explain`,
  String.raw`please explain`,
  String.raw`explain to me`,
  String.raw`explain this to me`,
  String.raw`what's the reasoning`,
  String.raw`what is the reasoning`,
  String.raw`how come`,
  String.raw`what's the logic`,
  String.raw`what is the logic`
];

const CODE = [
  String.raw`implement`,
  String.raw`build`,
  String.raw`create`,
  String.raw`develop`,
  String.raw`write code`,
  String.raw`coding`,
  String.raw`program`,
  String.raw`programming`,
  String.raw`scaffold`,
  String.raw`boilerplate`,
  String.raw`generate code`,
  String.raw`write a script`,
  String.raw`shell script`,
  String.raw`bash script`,
  String.raw`add (?:a )?(?:function|method|class|module|component|endpoint|route|handler|feature|test|unit test|integration test|hook|listener|middleware|validator|serializer|parser|CLI|command|subcommand|flag|option|table|column|index|migration|model|DTO|enum|struct|trait|interface|type|hook|reducer|selector|controller|service|repository|view|template|widget|page|screen|form|button|field|job|worker|lambda|webhook)`,
  String.raw`build (?:a )?(?:function|class|module|component|api|endpoint|feature|app|service|CLI|tool|script|parser|validator|middleware|pipeline|workflow|dashboard|page|form|bot|agent|integration|connector|adapter|plugin|extension|library|package|SDK|client|server|backend|frontend|microservice|daemon|worker|cron job|scheduler|queue consumer|webhook handler|REST API|GraphQL API|gRPC service)`,
  String.raw`create (?:a )?(?:function|class|module|component|api|endpoint|feature|script|file|service|app|tool|CLI|library|package|database|table|schema|migration|model|DTO|enum|struct|trait|interface|type|test|fixture|mock|stub|handler|listener|middleware|validator|parser|serializer|template|component|page|route|endpoint)`,
  String.raw`implement (?:a )?(?:function|class|module|component|api|endpoint|feature|algorithm|service|handler|middleware|auth flow|login flow|signup flow|payment flow|retry logic|cache layer|rate limiter|search|pagination|sorting|filtering|validation|sanitization|encryption|hashing|parser|serializer|CLI|SDK|client|server|integration|webhook|background job|cron job|state machine|event handler|websocket|socket|gRPC|protobuf|OpenAPI|GraphQL schema|REST endpoint)`,
  String.raw`refactor (?:the )?(?:code|function|class|module|component|service|handler|API)`,
  String.raw`unit test`,
  String.raw`integration test`,
  String.raw`e2e test`,
  String.raw`end-to-end test`,
  String.raw`test suite`,
  String.raw`write tests for`,
  String.raw`endpoint`,
  String.raw`route handler`,
  String.raw`REST API`,
  String.raw`GraphQL`,
  String.raw`gRPC`,
  String.raw`protobuf`,
  String.raw`OpenAPI`,
  String.raw`component`,
  String.raw`function`,
  String.raw`class`,
  String.raw`package`,
  String.raw`library`,
  String.raw`algorithm`,
  String.raw`data structure`,
  String.raw`SQL query`,
  String.raw`stored procedure`,
  String.raw`regex`,
  String.raw`regular expression`,
  String.raw`script`,
  String.raw`typescript`,
  String.raw`javascript`,
  String.raw`python`,
  String.raw`rust`,
  String.raw`golang`,
  String.raw`\bgo\b`,
  String.raw`java`,
  String.raw`kotlin`,
  String.raw`swift`,
  String.raw`ruby`,
  String.raw`php`,
  String.raw`c\+\+`,
  String.raw`csharp`,
  String.raw`\.net`,
  String.raw`scala`,
  String.raw`haskell`,
  String.raw`elixir`,
  String.raw`erlang`,
  String.raw`clojure`,
  String.raw`lua`,
  String.raw`perl`,
  String.raw`bash`,
  String.raw`powershell`,
  String.raw`dart`,
  String.raw`flutter`,
  String.raw`solidity`,
  String.raw`wasm`,
  String.raw`webassembly`,
  String.raw`react`,
  String.raw`vue`,
  String.raw`angular`,
  String.raw`svelte`,
  String.raw`astro`,
  String.raw`remix`,
  String.raw`next\.?js`,
  String.raw`nuxt`,
  String.raw`node\.?js`,
  String.raw`deno`,
  String.raw`bun`,
  String.raw`django`,
  String.raw`flask`,
  String.raw`fastapi`,
  String.raw`express`,
  String.raw`nestjs`,
  String.raw`spring boot`,
  String.raw`rails`,
  String.raw`laravel`,
  String.raw`symfony`,
  String.raw`tailwind`,
  String.raw`postgres`,
  String.raw`postgresql`,
  String.raw`mysql`,
  String.raw`sqlite`,
  String.raw`mongodb`,
  String.raw`redis`,
  String.raw`kafka`,
  String.raw`rabbitmq`,
  String.raw`websocket`,
  String.raw`serverless`,
  String.raw`lambda function`,
  String.raw`webhook handler`,
  String.raw`background job`,
  String.raw`cron job`,
  String.raw`event handler`,
  String.raw`state machine`,
  String.raw`middleware`,
  String.raw`database migration`,
  String.raw`schema migration`,
  String.raw`seed data`,
  String.raw`fixture`,
  String.raw`mock`,
  String.raw`stub`,
  String.raw`CLI tool`,
  String.raw`command line tool`,
  String.raw`TUI`,
  String.raw`parser for`,
  String.raw`codegen`,
  String.raw`ORM model`,
  String.raw`DTO`,
  String.raw`interface definition`,
  String.raw`type definition`,
  String.raw`enum`,
  String.raw`struct`,
  String.raw`trait`,
  String.raw`impl block`,
  String.raw`port to`,
  String.raw`convert to`,
  String.raw`translate to code`,
  String.raw`code (?:this|up|it)`,
  String.raw`make (?:a )?(?:function|class|script|component|service|API|endpoint|tool)`,
  String.raw`construct (?:a )?`,
  String.raw`prototype`,
  String.raw`POC`,
  String.raw`proof of concept`,
  String.raw`MVP`,
  String.raw`feature implementation`,
  String.raw`business logic`,
  String.raw`CRUD`,
  String.raw`auth middleware`,
  String.raw`JWT implementation`,
  String.raw`OAuth implementation`,
  String.raw`login flow`,
  String.raw`signup flow`,
  String.raw`payment integration`,
  String.raw`stripe integration`,
  String.raw`database schema`,
  String.raw`query builder`,
  String.raw`pagination`,
  String.raw`rate limiter`,
  String.raw`retry logic`,
  String.raw`circuit breaker`,
  String.raw`file upload`,
  String.raw`download handler`,
  String.raw`image processing`,
  String.raw`email template`,
  String.raw`notification service`,
  String.raw`HTML component`,
  String.raw`CSS styles`,
  String.raw`API client`,
  String.raw`SDK for`
];

const QUICK = [
  String.raw`quick(?:ly)?`,
  String.raw`real quick`,
  String.raw`super quick`,
  String.raw`short answer`,
  String.raw`one[- ]liner`,
  String.raw`one line`,
  String.raw`simple answer`,
  String.raw`small (?:change|fix|task|question|answer|update|favor|favour)`,
  String.raw`brief(?:ly)?`,
  String.raw`tldr`,
  String.raw`TL;DR`,
  String.raw`too long`,
  String.raw`just give me`,
  String.raw`in one sentence`,
  String.raw`minimal(?:ly)?`,
  String.raw`concise(?:ly)?`,
  String.raw`fast answer`,
  String.raw`don't over-explain`,
  String.raw`do not over-explain`,
  String.raw`skip the explanation`,
  String.raw`skip details`,
  String.raw`keep it short`,
  String.raw`keep it brief`,
  String.raw`tiny (?:change|fix|task|answer)`,
  String.raw`snippet`,
  String.raw`quick fix`,
  String.raw`quick question`,
  String.raw`yes or no`,
  String.raw`in a nutshell`,
  String.raw`bottom line`,
  String.raw`short version`,
  String.raw`no fluff`,
  String.raw`straight to the point`,
  String.raw`get to the point`,
  String.raw`cut to the chase`,
  String.raw`bullet points only`,
  String.raw`few words`,
  String.raw`couple of lines`,
  String.raw`one paragraph`,
  String.raw`super short`,
  String.raw`micro task`,
  String.raw`small tweak`,
  String.raw`minor change`,
  String.raw`quick check`,
  String.raw`quick look`,
  String.raw`rapid`,
  String.raw`fast`,
  String.raw`speed run`,
  String.raw`speedrun`,
  String.raw`asap`,
  String.raw`urgent but small`,
  String.raw`no details needed`,
  String.raw`short and sweet`,
  String.raw`pithy`,
  String.raw`punchy`,
  String.raw`one word answer`,
  String.raw`two sentences max`,
  String.raw`three bullets`,
  String.raw`elevator pitch length`,
  String.raw`tweet length`,
  String.raw`don't elaborate`,
  String.raw`do not elaborate`,
  String.raw`no preamble`,
  String.raw`abbreviated`,
  String.raw`ultra short`,
  String.raw`micro`,
  String.raw`nano`,
  String.raw`30 second answer`,
  String.raw`five second answer`,
  String.raw`rapid fire`,
  String.raw`cursory`,
  String.raw`superficial check`,
  String.raw`glance at`,
  String.raw`skim`,
  String.raw`high level only`,
  String.raw`just the answer`,
  String.raw`answer only`,
  String.raw`no essay`,
  String.raw`don't write a lot`,
  String.raw`keep it tiny`
];

const GHOST = [
  String.raw`Analyze GHOST live session`,
  String.raw`GHOST live session`,
  String.raw`GHOST session analysis`,
  String.raw`analyze (?:the )?GHOST session`,
  String.raw`GHOST telemetry`,
  String.raw`live GHOST`,
  String.raw`GHOST dashboard`,
  String.raw`GHOST metrics`,
  String.raw`GHOST monitoring`,
  String.raw`GHOST data`,
  String.raw`GHOST report`
];

export const TASK_PATTERN_SOURCES = {
  ask: routePattern(ASK),
  agent: routePattern(AGENT),
  multitask: routePattern(MULTITASK),
  debug: routePattern(DEBUG),
  review: routePattern(REVIEW),
  docs: routePattern(DOCS),
  plan: routePattern(PLAN),
  explain: routePattern(EXPLAIN),
  code: routePattern(CODE),
  quick: routePattern(QUICK),
  ghost: routePattern(GHOST)
};

const defaultPatterns = Object.fromEntries(
  Object.entries(TASK_PATTERN_SOURCES).map(([task, source]) => [task, new RegExp(source, "i")])
);

export async function classifyTask(text, config) {
  const customPatterns = config.routing?.taskPatterns ?? {};
  const patterns = Object.entries({ ...TASK_PATTERN_SOURCES, ...customPatterns }).reduce((acc, [task, pattern]) => {
    const source = pattern instanceof RegExp ? pattern.source : pattern;
    acc[task] = new RegExp(source, "ig");
    return acc;
  }, {});

  const scores = Object.entries(patterns).map(([task, pattern]) => ({
    task,
    score: (text.match(pattern) || []).length
  }));
  scores.sort((a, b) => b.score - a.score);
  const match = scores.find((item) => item.score > 0);
  return match?.task ?? "code";
}

export { defaultPatterns };
